:idprefix:
:idseparator: -

:portal_dialog_service_url: xref:documentation:onecx-portal-ui-libs:service/portal-dialog-service.adoc

== Customize form fields

The form fields of the dialog need to be adapted

[#action-1]
=== ACTION C1: Extend schemas inside OpenAPI
_Adapt in File:_  `+<feature>-bff.yaml+`

The generator creates **4 new components** in the OpenAPI specification for Create/Update Request & Response.

[NOTE]
====
The Request objects are referencing the xref:angular/glossary.adoc#resource[`Resource`], its properties are used by the form.
You can modify it, but check xref:angular/glossary.adoc#resource[`here`] for side effects.

Changes to the response object itself require modification in the response handling. By default other response properties (apart from resource) are ignored.
==== 

[#action-2]
=== ACTION C2: Add form fields to html component
_Adapt in File:_  `+<feature>-create-update.component.html+`

Add new form fields similar to the generated example. Please, ensure that form control names match the xref:angular/glossary.adoc#resource[`Resource`] properties.

.Example resource
[source,yaml]
----
Example:
type: object
required:
    - id
properties:
    modificationCount:
        type: integer
        format: int32
    id:
        type: string
    name:
        type: string
----

.Example form field
[source,html]
----
<div [title]="'EXAMPLE_CREATE_UPDATE.FORM.NAME' | translate">
    <span class="p-float-label" controlErrorAnchor>
    <input
        pInputText
        type="text"
        id="example_detail_form_name"
        class="w-full pt-3 pb-2"
        formControlName="name"
    />
    <label class="ocx-required-label" for="example_detail_form_name">
        {{ 'EXAMPLE_CREATE_UPDATE.FORM.NAME' | translate }}</label
    >
    </span>
</div>
----

[#action-3]
=== ACTION C3: Add form fields to ts component
_Adapt in File:_  `+<feature>-create-update.component.ts+`

Add new form controls to the formGroup. Please, ensure that form control names match the properties of your xref:angular/glossary.adoc#resource[`Resource`].

Use appropriate validators if required.

.Example resource
[source,yaml]
----
Example:
type: object
required:
    - id
properties:
    modificationCount:
        type: integer
        format: int32
    id:
        type: string
    name:
        type: string
----

.Example form control
[source,js]
----
this.formGroup = new FormGroup({
    name: new FormControl(null, [Validators.maxLength(255)]),
    ...
});
----

NOTE: To configure the dialog or modify its contents, please refer to the {portal_dialog_service_url}[PortalDialogService docs].
